require('core/mappings')
require('core/options')
require('core/autocmds')
require('core/colorscheme')
require('core/lualine')
require('lsp/lspconfig')
require('lsp/nvim-cmp')
require('lsp/nvim-dap')
require('plugins/plenary')
require('plugins/telescope')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/nvim-autopairs')
require('plugins/bufferline')
require('plugins/alpha-nvim')
require('plugins/indent-blankline')
require('plugins/which-key')

